package com.centron.sentinel.contract

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject

/**
 * SENTINEL CONTRACT v1 — generated by hand from contract.json ($defs).
 *
 * Source of truth is contract.json. If this file disagrees with it, this file
 * is wrong. Do not "fix" a decode failure by loosening a type here; raise it.
 *
 * NOTE: contracts.md prose describes approve_action as
 *   { approval_id, decision: "approve"|"deny", biometric_assertion, client_ts }
 * but contract.json AND samples/approve_action.json both say
 *   { approval_id, event_id, decision: "approved"|"denied", biometric: bool }
 * Two machine-readable sources agree, so we follow them. Flagged to Shan.
 */

/** Decoder for every frame on the wire. ignoreUnknownKeys is non-negotiable:
 *  a field added Saturday night must not require reinstalling the demo app. */
val SentinelJson: Json = Json {
    ignoreUnknownKeys = true
    classDiscriminator = "type"
    encodeDefaults = true
    explicitNulls = false
}

// ---------------------------------------------------------------- enums

@Serializable
enum class Severity {
    /** Logs silently. Never spoken. */
    @SerialName("info") INFO,

    /** Queues TTS behind current playback. */
    @SerialName("low") LOW,

    /** Interrupts the queue. */
    @SerialName("high") HIGH,

    /** Interrupts, plus alarm tone, plus haptic. */
    @SerialName("critical") CRITICAL;

    /** The one rule the contract states twice: never speak info. */
    val isSpoken: Boolean get() = this != INFO
}

@Serializable
enum class Playbook {
    @SerialName("block_ip") BLOCK_IP,
    @SerialName("rate_limit") RATE_LIMIT,
    @SerialName("isolate_host") ISOLATE_HOST,
    @SerialName("watch") WATCH,
    @SerialName("notify_only") NOTIFY_ONLY,
    @SerialName("revoke_session") REVOKE_SESSION,
    @SerialName("snapshot_evidence") SNAPSHOT_EVIDENCE,
}

@Serializable
enum class ActionStatus {
    @SerialName("auto_executed") AUTO_EXECUTED,
    @SerialName("pending_approval") PENDING_APPROVAL,
    @SerialName("approved") APPROVED,
    @SerialName("denied") DENIED,
    @SerialName("expired") EXPIRED,
    @SerialName("failed") FAILED,
}

@Serializable
enum class AudioStatus {
    @SerialName("ready") READY,
    @SerialName("pending") PENDING,
    @SerialName("failed") FAILED,
    @SerialName("suppressed") SUPPRESSED,
}

@Serializable
enum class EscalationGate {
    @SerialName("unknown_pattern") UNKNOWN_PATTERN,
    @SerialName("novelty") NOVELTY,
    @SerialName("correlation") CORRELATION,
    @SerialName("schema_failure") SCHEMA_FAILURE,
    @SerialName("blast_radius") BLAST_RADIUS,
    @SerialName("severity_floor") SEVERITY_FLOOR,
    @SerialName("low_confidence") LOW_CONFIDENCE,
    @SerialName("model_self_report") MODEL_SELF_REPORT,
}

@Serializable
enum class EscalationState {
    @SerialName("none") NONE,
    @SerialName("pending") PENDING,
    @SerialName("answered") ANSWERED,
    @SerialName("unreachable") UNREACHABLE,
}

@Serializable
enum class SubsystemStatus {
    @SerialName("ok") OK,
    @SerialName("degraded") DEGRADED,
    @SerialName("unreachable") UNREACHABLE,
}

@Serializable
enum class Decision {
    @SerialName("approved") APPROVED,
    @SerialName("denied") DENIED,
}

// ---------------------------------------------------------------- event payload

@Serializable
data class Entities(
    val src_ips: List<String> = emptyList(),
    val dst_hosts: List<String> = emptyList(),
    val users: List<String> = emptyList(),
    val ports: List<Int> = emptyList(),
)

@Serializable
data class Source(
    val kind: String,
    val collector: String,
    val raw_count: Int,
)

@Serializable
data class Window(
    val start: String,
    val end: String,
)

@Serializable
data class AudioRef(
    val status: AudioStatus,
    val audio_id: String,
    val url: String? = null,
    val mime: String? = null,
    val duration_ms: Int? = null,
    val sha256: String? = null,
    val cache_key: String? = null,
)

@Serializable
data class Escalation(
    val escalated: Boolean,
    val gate: EscalationGate? = null,
    val reason: String? = null,
    val state: EscalationState = EscalationState.NONE,
    val verdict: String? = null,
)

/**
 * params is a discriminated union per playbook. The phone only needs the
 * playbook name and requires_approval (Contract 2), so params stays a raw
 * JsonObject rather than seven Kotlin types we would never branch on.
 */
@Serializable
data class ActionRef(
    val playbook: Playbook,
    val params: JsonObject,
    val status: ActionStatus,
    val requires_approval: Boolean,
    val expires_at: String? = null,
    val approval_id: String? = null,
)

@Serializable
data class EventData(
    val event_id: String,
    val signature: String,
    val severity: Severity,
    val title: String,
    val internal_log: String,
    val tts_summary: String,
    val confidence: Double,
    val source: Source,
    val window: Window,
    val entities: Entities = Entities(),
    val audio: AudioRef? = null,
    val escalation: Escalation? = null,
    val action: ActionRef? = null,
    /** Fail-closed flag. Phone renders an unreviewed badge when false. */
    val reviewed: Boolean = false,
)

// ---------------------------------------------------------------- other payloads

@Serializable
data class PipelineStatus(
    val log_source: SubsystemStatus = SubsystemStatus.OK,
    val ollama: SubsystemStatus = SubsystemStatus.OK,
    val tts: SubsystemStatus = SubsystemStatus.OK,
    val claude: SubsystemStatus = SubsystemStatus.OK,
)

@Serializable
data class HeartbeatData(
    val interval_s: Int,
    val uptime_s: Long,
    val last_event_seq: Long,
    val queue_depth: Int,
    val pipeline: PipelineStatus,
)

@Serializable
data class HelloData(
    val server_id: String,
    val heartbeat_interval_s: Int,
    val last_event_seq: Long,
    val contract_version: String? = null,
    val resync_buffer_max: Int? = null,
)

@Serializable
data class ActionUpdateData(
    val event_id: String,
    val playbook: Playbook,
    val status: ActionStatus,
    val approval_id: String? = null,
    val expires_at: String? = null,
    val reason: String? = null,
)

@Serializable
data class AudioReadyData(
    val event_id: String,
    val audio: AudioRef,
)

@Serializable
data class AckData(
    val seq: Long,
    val event_id: String? = null,
)

@Serializable
data class ApproveActionData(
    val approval_id: String,
    val event_id: String,
    val decision: Decision,
    val biometric: Boolean,
)

@Serializable
data class ResyncData(
    val since_seq: Long,
)

// ---------------------------------------------------------------- envelopes

@Serializable
sealed class ServerFrame {
    abstract val v: Int
    abstract val seq: Long
    abstract val ts: String
}

@Serializable
@SerialName("hello")
data class HelloFrame(
    override val v: Int = 1,
    override val seq: Long,
    override val ts: String,
    val data: HelloData,
) : ServerFrame()

@Serializable
@SerialName("event")
data class EventFrame(
    override val v: Int = 1,
    override val seq: Long,
    override val ts: String,
    val data: EventData,
) : ServerFrame()

@Serializable
@SerialName("heartbeat")
data class HeartbeatFrame(
    override val v: Int = 1,
    override val seq: Long,
    override val ts: String,
    val data: HeartbeatData,
) : ServerFrame()

@Serializable
@SerialName("action_update")
data class ActionUpdateFrame(
    override val v: Int = 1,
    override val seq: Long,
    override val ts: String,
    val data: ActionUpdateData,
) : ServerFrame()

@Serializable
@SerialName("audio_ready")
data class AudioReadyFrame(
    override val v: Int = 1,
    override val seq: Long,
    override val ts: String,
    val data: AudioReadyData,
) : ServerFrame()

@Serializable
sealed class ClientFrame {
    abstract val v: Int
    abstract val seq: Long
    abstract val ts: String
}

@Serializable
@SerialName("ack")
data class AckFrame(
    override val v: Int = 1,
    override val seq: Long,
    override val ts: String,
    val data: AckData,
) : ClientFrame()

@Serializable
@SerialName("approve_action")
data class ApproveActionFrame(
    override val v: Int = 1,
    override val seq: Long,
    override val ts: String,
    val data: ApproveActionData,
) : ClientFrame()

@Serializable
@SerialName("resync")
data class ResyncFrame(
    override val v: Int = 1,
    override val seq: Long,
    override val ts: String,
    val data: ResyncData,
) : ClientFrame()
